---
- name: Create /mnt/hgfs directory for synced folder mounts.
  file:
    path: /mnt/hgfs
    state: directory
  become: yes

- name: Install open-vm-tools.
  apt: name=open-vm-tools state=present
  become: yes
  when: vmware_install_open_vm_tools

# Install VMware Tools if not using open-vm-tools.
- block:
  - name: Create temporary directories for VMware tools.
    file:
      path: "/tmp/{{ item }}"
      state: directory
    become: yes
    with_items:
      - vmfusion
      - vmfusion-archive

  - name: Mount VMware tools.
    mount:
      name: /tmp/vmfusion
      src: /home/vagrant/linux.iso
      fstype: iso9660
      state: mounted
    become: yes

  - name: Decompress VMware Tools installer into archive folder.
    shell: tar xzf /tmp/vmfusion/VMwareTools-*.tar.gz -C /tmp/vmfusion-archive
    become: yes

  - name: Run the VMware tools installer.
    shell: /tmp/vmfusion-archive/vmware-tools-distrib/vmware-install.pl --default
    become: yes
    register: vmtools_installer_output

  - name: Run the VMware tools installer with --force-install.
    shell: /tmp/vmfusion-archive/vmware-tools-distrib/vmware-install.pl --default --force-install
    become: yes
    when: vmtools_installer_output.stdout.find('open-vm-tools') != -1

  - name: Unmount VMware tools.
    mount:
      name: /tmp/vmfusion
      src: /home/vagrant/linux.iso
      fstype: iso9660
      state: absent
    become: yes

  - name: Remove temporary directories for VMware tools.
    file:
      path: "/tmp/{{ item }}"
      state: absent
    become: yes
    with_items:
      - vmfusion
      - vmfusion-archive

  - name: Delete VMWare Tools.
    file:
      path: /home/vagrant/linux.iso
      state: absent
    become: yes
  when: not vmware_install_open_vm_tools
